---
title: "Introduction to U.S. Health Care"
---

## Objectives
- Recall the total annual expenditures on health and health care in the U.S.
- Compare U.S. health expenditures and quality to that of other countries
- Explain the debate surrounding the role of prices in U.S. health care expenditures
- Summarize some of the unique economic features of the U.S. health care market

## Activities 
- Review the [syllabus](/syllabus.html), [schedule](/schedule.html), and [assignments](/assignments.html) pages for this class...just to get a feel for the site and how to navigate all of the information.
- Discussion of U.S. health care expenditures and quality
- Overview of class and introductions
- Complete the [Math Review](/resource/review1) and [Practice Problems](/resource/review2)


## Supplemental Info
- <i class="fas fa-book"></i> These articles are more of a guide for the semester. We'll touch on most of the topics covered in the articles over the next several weeks. Reading these papers now can really help to prepare you for the whole semester.
    - [@arrow1963]. Link to paper [here](https://www.jstor.org/stable/1812044).
    - [@gaynor2015jel]. Link to paper [here](https://www.aeaweb.org/articles?id=10.1257/jel.53.2.235).
- <i class="fas fa-external-link-square-alt"></i> Supplemental information we'll use throughout this module.
- Data from [Gapminder](https://www.gapminder.org/)
- For a good discussion of hospital prices and something called "charges", see [@anderson2003]. Link to paper [here](https://www.healthaffairs.org/doi/10.1377/hlthaff.22.3.89).
- Healthcare triage videos: [The Healthcare System of the United States](https://www.youtube.com/watch?v=yN-MkRcOJjY) and [Why Does the US Spend So Much On Healthcare?](https://www.youtube.com/watch?v=tFtAohYPSFc)
- Time, 2013. [Bitter Pill: Why Medical Bills are Killing Us](https://time.com/198/bitter-pill-why-medical-bills-are-killing-us/)
- Forbes, 2018. [Healthcare: It's the prices, stupid. Isn't it?](https://www.forbes.com/sites/elliekincaid/2018/03/13/healthcare-its-the-prices-stupid-isnt-it/#52a5fda3198a)
- Blog, Random Critical Analysis, November 2018. ["Why everything you have said about the determinants of health expenditure is wrong in one million charts: A response to Noah Smith."](https://randomcriticalanalysis.com/2018/11/19/why-everything-you-know-about-healthcare-is-wrong-in-one-million-charts-a-response-to-noah-smith/)